name: CI test for lrc-plotter                                                   
on:                                                                             
  push:                                                                         
    branches: [ master ]                                                        
  pull_request:                                                                 
    branches: [ master ]                                                        
jobs:                                                                           
  poetry-install:                                                               
    runs-on: ubuntu-latest                                                      
    steps:                                                                      
    - name: Set up Python                                                       
      uses: actions/setup-python@v2                                             
      with:                                                                     
        python-version: "3.9"                                                   
    - name: Source branch checkout                                              
      uses: actions/checkout@v2                                                 
    - name: Set up system requirements                                          
      run: curl -sSL https://install.python-poetry.org | python3 - --version 1.3.1
    - name: poetry install check                                                
      run: poetry install
